
//Register
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "fullname": "test",
    "nickname": "test",
    "password": "lich",
    "avatar" : null
}

###
PUT http://localhost:8000/api/user/update/6331c525ea8cd1a1bf7cbddc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzMxNmM3YzI4MGU0ZDY5MDZjMjFjNzQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NjQyMDA4MDF9.4yhzrVWSqO-IGy9lRgphYj615ckpLvsuIjpnYVF1cWg

{
    "fullname": "Nguyễn Dũng"
}

###
PUT http://localhost:5000/api/videos/update/6334690613ab6cd4e08cb69e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzMxNmM3YzI4MGU0ZDY5MDZjMjFjNzQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NjQyMDA4MDF9.4yhzrVWSqO-IGy9lRgphYj615ckpLvsuIjpnYVF1cWg

{
    "title": "Test"
}




###
GET http://localhost:5000/api/videos/foryou?userId=6336ec4e4cf1eb964f2a45e3&page=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzMxNmM3YzI4MGU0ZDY5MDZjMjFjNzQiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NjQyMDA4MDF9.4yhzrVWSqO-IGy9lRgphYj615ckpLvsuIjpnYVF1cWg


###
GET https://tiktok.fullstack.edu.vn/api/users/search?q=hoa&type=less

###

http://localhost:8000/api/videos?type=home&userId=62cb773ed852c4a099ac837a

###


#Tìm kiếm videos bằng nickname
http://localhost:5000/api/videos/bichcot

